### ISSUE TITLE
General doubts

### ISSUE THREAD

**Issue by just-hms** [just-hms/large-scale-multistructure-db#28]
- [ ] How to retrieve different data based on the same collection at this moment
    
    ex: `barberShop` data is different based on the logged user
    
- [x] General code review
- [ ] How to implement `Reviews` and `Appointments` pagination

**Comment by b0-n0-b0** [comment]
how the fuck do we manage having a lot of reviews if we retrieve them at the start of the connection?

**Comment by SilverBeamx** [comment]
Closing as we decided to not implement pagination
